export enum TypeBackgroundColor {
    bug = '#D9E29A',
    dark = '#A1A1A1',
    dragon = '#B3A8F2',
    electric = '#FCEB8A',
    fairy = '#E8C9E8',
    fighting = '#D1AA9E',
    fire = '#F18D6E',
    flying = '#BAC7E9',
    ghost = '#8B8BBE',
    grass = '#AEDB8E',
    ground = '#D9C98E',
    ice = '#B3E0FD',
    normal = '#DAD7D1',
    poison = '#C6A9C6',
    psychic = '#F0A4B6',
    rock = '#C9B68D',
    steel = '#CFCFCF',
    water = '#A0E6FF'
}
